---

- name: Create authorized_keys dir
  file:
    path:   /etc/ssh/authorized_keys
    state:  directory
    owner:  root
    group:  root
    mode:   0755
  changed_when: false

# TODO only copy if doesn't exist

- name: Copy current authorized_keys into centralized location
  copy:
    src:        "/home/{{ ansible_user }}/.ssh/authorized_keys"
    dest:       "/etc/ssh/authorized_keys/{{ ansible_user }}"
    remote_src: true
    force:      no
    owner:      "{{ ansible_user }}"
    group:      "{{ ansible_user }}"
    mode:       0400

- name: ensure sshd is configured
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/ssh/sshd_config
  notify:
    - reloaded sshd
